# Generated by Django 2.1.7 on 2019-11-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='img/diy')),
                ('desc', models.CharField(max_length=1000)),
                ('mentor', models.CharField(max_length=50)),
                ('members', models.CharField(max_length=200)),
                ('file', models.FileField(default='', upload_to='docs/diy')),
            ],
        ),
        migrations.CreateModel(
            name='FYI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(default='', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
