# Generated by Django 2.1.7 on 2020-02-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('sponsor_type', models.CharField(blank=True, max_length=150, null=True)),
                ('website', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='sponsors/%Y/%m/%d')),
            ],
        ),
    ]
