# Generated by Django 2.1.7 on 2020-02-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_pages', '0002_auto_20200218_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='roboExpoAbstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('xfile', models.FileField(blank=True, null=True, upload_to='robothonExpoAbstract/')),
            ],
        ),
        migrations.CreateModel(
            name='robothonAbstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('xfile', models.FileField(blank=True, null=True, upload_to='robothonAbstract/')),
            ],
        ),
    ]
