# Generated by Django 2.1.7 on 2020-02-18 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roboPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='portaluser',
            old_name='verified',
            new_name='is_admin',
        ),
        migrations.AddField(
            model_name='portaluser',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='joined_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='user_team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
