# Generated by Django 2.1.7 on 2020-02-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboPortal', '0002_auto_20200218_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='branch',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='college',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
