# Generated by Django 2.1.7 on 2020-02-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboPortal', '0003_auto_20200219_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
