# Generated by Django 2.1.11 on 2020-02-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboPortal', '0005_auto_20200212_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
