# Generated by Django 2.1.11 on 2020-02-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboPortal', '0006_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
