# Generated by Django 2.1.11 on 2020-02-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboPortal', '0007_portaluser_is_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
