# Generated by Django 2.1.7 on 2020-02-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roboPortal', '0008_team_selected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.RemoveField(
            model_name='userlink',
            name='link',
        ),
        migrations.RemoveField(
            model_name='portaluser',
            name='verified',
        ),
        migrations.DeleteModel(
            name='UserLink',
        ),
    ]
