# Generated by Django 2.1.7 on 2020-02-16 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roboPortal', '0010_auto_20200216_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member1',
        ),
        migrations.AddField(
            model_name='team',
            name='member1',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
