# Generated by Django 2.1.7 on 2020-02-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roboPortal', '0011_auto_20200216_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='member1',
            new_name='member',
        ),
    ]
